// export { default as Compact } from './components/Compact.vue'
// export { default as Grayscale } from './components/Grayscale.vue'
// export { default as Material } from './components/Material.vue'
// export { default as Slider } from './components/Slider.vue'
// export { default as Swatches } from './components/Swatches.vue'
// export { default as Photoshop } from './components/Photoshop.vue'
// export { default as Sketch } from './components/Sketch.vue'
// export { default as Chrome } from './components/Chrome.vue'
// export { default as Alpha } from './components/common/Alpha.vue'
// export { default as Checkboard } from './components/common/Checkboard.vue'
// export { default as EditableInput } from './components/common/EditableInput.vue'
// export { default as Hue } from './components/common/Hue.vue'
// export { default as Saturation } from './components/common/Saturation.vue'
import Chrome from './components/chrome.vue'
import Compact from './components/compact.vue'
import Grayscale from './components/grayscale.vue'
import Material from './components/material.vue'
import Photoshop from './components/photoshop.vue'
import Sketch from './components/sketch.vue'
import Slider from './components/slider.vue'
import Swatch from './components/swatch.vue'
import Twitter from './components/twitter.vue'

export { Chrome, Compact, Grayscale, Material, Photoshop, Sketch, Slider, Swatch, Twitter }
